name: Static Type Checks
on: [push, pull_request]
jobs:
  mypy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Run checks
        run: |
          echo "MOCK"
  status:
    name: Static Type Checks
    runs-on: ubuntu-latest
    needs: mypy
    steps:
      - run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "Static Type Checks",
            "state": "success",
            "description": "Static type checks passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
